services:
  ofpnd-backend:
    container_name: ofpnd-backend
    image: ofpnd-backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_HOST: ${DB_HOST:-postgres_db}
      DB_PORT: 5432
      DB_NAME: ${DB_NAME:-ofpnd_dev}
      STAGE: ''
    ports:
      - "8003:8000"