version = 0.1
[default.deploy.parameters]
stack_name = "ofp-layers"
resolve_s3 = true
s3_prefix = "ofp-layers"
region = "us-east-1"
profile = "khartes"
capabilities = "CAPABILITY_IAM"
image_repositories = []
